(function () {
  "use strict";
  const {Config:C,Game:G,Storage:S}=Shogun, app=document.getElementById('app'), modal=document.getElementById('modal');
  const store=S.createStorage(), loaded=store.load();
  let saved=loaded.state,state=null,saveError=loaded.error||'',mode='',pages=[],page=0,returnFocus=null,lastClick=-Infinity,message='列をタップ・クリック／1～5キー',placed=-1,freshWin=false;
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const type=c=>C.CASTLE_COLORS.find(t=>t.id===c.color);
  const button=(label,action,secondary=false)=>`<button class="button ${secondary?'secondary':'primary'}" data-action="${action}">${label}</button>`;
  const announce=s=>{document.getElementById('announcement').textContent=s;};
  function castle(c,large=false){const t=type(c);return `<span class="castle ${large?'current-art':''}" aria-label="${c.number}、${t.name}"><span class="castle-face"><img src="${t.image}" alt="" width="24" height="24"><b>${c.number}</b></span><span class="kind">${large?t.name:t.short}</span></span>`;}
  const scores=()=>`<div class="scores">${state.scores.map((n,i)=>`<span>第${i+1}戦 <b>${n===null?(i===state.battle-1?'累積 '+state.battleScore:'—'):n+'点'}</b></span>`).join('')}<span>合計 <b>${G.totalScore(state)}点</b></span></div>`;
  function theme(){document.body.classList.toggle('bonus',!!state?.bonusStage);}
  function persist(){const r=store.save(state);saveError=r.ok?'':r.error;saved=G.clone(state);}
  function close(){modal.close();mode='';if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});}
  function open(kind,html){if(!modal.open)returnFocus=document.activeElement;mode=kind;modal.innerHTML=html;if(!modal.open)modal.showModal();modal.querySelector('button')?.focus({preventScroll:true});}
  function title(){state=null;theme();close();app.innerHTML=`<main class="title-page"><section class="title-hero"><span class="eyebrow">数字を読み、五段を築け</span><h1>五段重ね将軍</h1><div class="title-castles">${C.CASTLE_COLORS.map((t,i)=>castle({number:[5,15,25][i],color:t.id},true)).join('')}</div><p>同じ城をそろえ、三戦を戦い抜く。</p></section><nav class="title-actions">${saved?button(saved.phase===G.Phase.GAME_RESULT?'前回の結果を見る':'つづきから','RESUME'):''}${button(saved?'最初から遊ぶ':'はじめる','NEW',!!saved)}${button('遊び方','HELP',true)}${saveError?button('保存について（要確認）','SAVE_INFO',true):''}</nav></main>`;}
  function render(){theme();const info=G.score(state.columns),active=state.phase===G.Phase.PLAYING,options=active?G.available(state):[];
    app.innerHTML=`<main class="game-page"><header><div class="headline"><h1>五段重ね将軍 <small>第${state.battle}戦</small></h1><span class="stage">${state.bonusStage?'ボーナスステージ':'三戦の城積み'}</span></div>${scores()}</header><div class="game-body"><section class="board" aria-label="下から上に積む5本の城列">${state.columns.map((col,i)=>{const ok=options.includes(i),top=col.at(-1),reason=col.length===C.MAX_STACK_HEIGHT?'満杯':top?`${top.number}より大`:'空列';return `<button class="column ${ok?'available':''} ${G.isMono(col)?'mono':''} ${placed===i?'placed':''}" data-column="${i}" aria-label="第${i+1}列、${ok?'置ける':reason}、${col.length}城${top?'、最上段'+top.number:''}" aria-disabled="${!ok}"><span class="column-title">第${i+1}列</span><span class="stack">${Array.from({length:C.MAX_STACK_HEIGHT},(_,j)=>`<span class="slot ${j===col.length-1?'top-castle':''}">${col[j]?castle(col[j]):'<span class="empty">・</span>'}</span>`).join('')}</span><span class="column-status">${ok?'置ける':reason}${G.isMono(col)?'<em>同種5段</em>':G.isFour(col)?'<em>4段＋5</em>':'<em>　</em>'}</span></button>`;}).join('')}</section><aside class="control-panel"><div class="current"><small>${active?'次に置く城':state.current?'置けなかった城':'25城制覇'}</small>${state.current?castle(state.current,true):'<b>完成</b>'}</div><div class="board-info"><div class="count"><strong>${info.castles} / ${G.TOTAL}城</strong> <span>倍率 ×${info.multiplier}</span></div><div class="score-preview">盤面見込み <strong>${info.points}点</strong></div><div class="four-info">同種4段 ＋${info.fourBonus}点${info.castles<C.MIN_SCORE_CASTLES?'（仮）':''}</div><small>${info.castles<C.MIN_SCORE_CASTLES?'15城未満で終了すると失効':'盤面終了時に加算'}</small><small>配置可能：${options.map(i=>i+1).join('・')||'なし'}</small></div><p class="message" role="status">${escape(saveError?'保存できません。詳細を確認':message)}</p><nav class="tools">${button('遊び方','HELP',true)}${button('詳細','DETAILS',true)}</nav></aside></div></main>`;
    if(active){if(modal.open)close();}else result();
  }
  function cause(){const c=state.result?.blockedCastle;return c?`<div class="blocked-castle"><b>置けなかった城：${c.number}</b><span>${type(c).name}</span><small>全列が満杯、または最上段が${c.number}以上</small></div>`:'';}
  function result(){const r=state.result,win=state.phase===G.Phase.WIN,final=state.phase===G.Phase.GAME_RESULT;
    open('RESULT',`<section class="result-summary"><h2 id="modal-title">${win?'勝ち戦！':final?'三戦の戦績':`第${state.battle}戦 終了`}</h2>${win?'<div class="bonus-banner">ボーナスステージ</div>':''}${final?`<small>五段重ね将軍・最終得点</small>${scores()}<div class="result-number">${state.finalScore}点</div><div class="rating"><small>あなたの評価</small><b>${G.rating(state.finalScore)}</b></div>`:`<p>${win?(r.winReason==='FULL_BOARD'?'25城制覇':`同種5段達成・${r.castles}城`):`${r.castles}城`}</p><div class="result-number">${win?'+':''}${r.points}点</div><p class="result-total">${win?`第${state.battle}戦 累積 ${state.battleScore}点`:`保持 ${state.battleScore-r.points} ＋ 今回 ${r.points} ＝ ${state.battleScore}点`}</p>${!r.base&&r.fourBonus?`<small>仮加点＋${r.fourBonus}点は失効</small>`:''}`}${cause()}</section><nav class="result-actions">${win?button(r.wasBonus?'ボーナスステージを続ける':'ボーナスステージへ','CONTINUE'):final?button('もう一度遊ぶ','NEW'):button(`第${state.battle+1}戦へ`,'NEXT_BATTLE')}${button('詳細','DETAILS',true)}${final?button('タイトル','TITLE',true):''}</nav>`);
  }
  const helpPages=[['城を積もう','5列に各5城まで。下から上へ、数字を大きくします。例：3 → 8 → 14。空列にはどの数字でも置けます。'],['3種類の城','イスラム・西洋・日本の城が同じ確率で出ます。種類が同じでも、小さい数字や同じ数字は上に置けません。'],['最初の5手','1～25は各1回。最初の5手は1～20、6手目から21～25も出ます。見えるのは現在の城だけです。'],['まずは15城','14城以下で詰まると盤面0点。同種4段の仮加点も失います。過去の勝ち戦の得点は残ります。'],['同種4段で＋5点','下から4城が同じ種類なら各列1回＋5点。5城目が別種でも残ります。上の4城だけが同じ場合は対象外です。'],['同種5段で倍率','完成列0／1／2／3／4／5列で ×1／2／3／4／5／10。15城以上なら城数×倍率＋4段加点。＋5点に倍率はかけません。'],['勝ち戦の条件','25城完成で即座に勝ち戦。15城以上・同種5段ありなら、置けなくなった時点で勝ち戦です。置ける間は続けます。'],['ボーナスステージ','勝ち戦の得点を加算し、同じ戦を新盤面で続けます。抽選と得点式は同じ。勝ち戦でなければ配置不能時に自動で戦終了です。'],['三戦で評価','戦終了が3回で最終結果。3戦合計で足軽から天下統一大将軍まで評価します。勝ち戦は戦終了に数えません。'],['操作と保存','列をタップ・クリック、または1～5キー。TabとEnter／Spaceも使えます。状態は自動保存。続きから同じ城で再開できます。']];
  function paged(kind,list){pages=list;page=0;mode=kind;drawPage();}
  function drawPage(){const kind=mode;open(kind,`<section class="page-content"><small>${page+1} / ${pages.length}</small><h2 id="modal-title">${escape(pages[page][0])}</h2><p>${escape(pages[page][1])}</p></section><nav class="page-actions">${button('前へ','PREV',true)}${button('次へ','NEXT',true)}${button('戻る','CLOSE_HELP',true)}</nav>${kind==='DETAILS'&&page===pages.length-1?button('タイトルへ','TITLE',true):''}`);modal.querySelector('[data-action="PREV"]').disabled=page===0;modal.querySelector('[data-action="NEXT"]').disabled=page===pages.length-1;modal.querySelector('[data-action="CLOSE_HELP"]').focus({preventScroll:true});}
  function details(){const r=G.score(state.columns);paged('DETAILS',[['得点の内訳',`${r.base?`${r.castles}城 × ${r.multiplier} ＋ ${r.fourBonus} ＝ ${r.points}点。4段加点には倍率をかけません。`:`${r.castles}城。15城未満なので盤面は0点です。仮加点＋${r.fourBonus}点も終了時に失効します。`} 戦累積 ${state.battleScore}点／合計 ${G.totalScore(state)}点。`],['参考記録',`勝ち戦 ${state.wins}回。最高積載 ${state.best}城。${r.mono&&r.base&&state.phase===G.Phase.PLAYING?'同種5段達成済み。配置不能時に勝ち戦です。':'数字と種類を見て、次の一手を考えましょう。'}`],['自動保存',saveError||'この端末・ブラウザに保存しています。再開時の城や得点は同じです。別端末への同期はありません。'],['ゲームを中断','タイトルに戻っても保存した進行は残ります。「つづきから」で再開できます。']]);}
  function start(){state=G.newGame();message='列をタップ・クリック／1～5キー';placed=-1;persist();close();render();}
  function apply(action){const before=state,r=G.transition(state,action);if(!r.changed){if(action.type==='PLACE'){message=state.columns[action.column]?.length===C.MAX_STACK_HEIGHT?'ここには置けません。満杯です':'ここには置けません。最上段より大が必要';render();announce(message);}return;}state=r.state;freshWin=state.phase===G.Phase.WIN;placed=action.type==='PLACE'?action.column:-1;message='列をタップ・クリック／1～5キー';if(placed>=0&&G.isFour(state.columns[placed])&&!G.isFour(before.columns[placed]))message='同種4段 ＋5点！';if(placed>=0&&G.isMono(state.columns[placed]))message='同種5段完成！ 配置不能時に勝ち戦';persist();render();if(freshWin)modal.querySelector('.bonus-banner')?.classList.add('celebrate');freshWin=false;if(!modal.open)document.querySelector(`[data-column="${Math.max(0,placed)}"]`).focus({preventScroll:true});announce(`${message} ${G.count(state)}城。${state.phase===G.Phase.WIN?'勝ち戦、ボーナスステージ。':state.phase===G.Phase.PLAYING?'': '戦終了。'}${state.phase===G.Phase.GAME_RESULT?`最終得点${state.finalScore}点、あなたの評価は${G.rating(state.finalScore)}。`:''}${state.current?`${state.phase===G.Phase.PLAYING?'次の城':'置けなかった城'}は${state.current.number}、${type(state.current).name}`:''}`);}
  document.addEventListener('click',e=>{const t=e.target.closest('[data-action],[data-column]');if(!t||(modal.open&&!modal.contains(t)))return;if(performance.now()-lastClick<220)return;lastClick=performance.now();if(t.dataset.column!==undefined)return apply({type:'PLACE',column:Number(t.dataset.column)});const a=t.dataset.action;
    if(a==='HELP')return paged('HELP',helpPages);
    if(a==='DETAILS')return details();
    if(a==='SAVE_INFO')return paged('INFO',[['保存について',saveError]]);
    if(a==='PREV'||a==='NEXT'){page+=a==='NEXT'?1:-1;return drawPage();}
    if(a==='CLOSE_HELP'||a==='CANCEL_NEW'){close();if(state&&state.phase!==G.Phase.PLAYING)result();return;}
    if(a==='TITLE')return title();
    if(a==='RESUME'){state=G.clone(saved);placed=-1;return render();}
    if(a==='NEW'){if(!state&&saved&&saved.phase!==G.Phase.GAME_RESULT)return open('CONFIRM',`<section><h2 id="modal-title">最初から遊びますか？</h2><p>保存したゲームの得点と記録をリセットします。</p></section><nav>${button('新しく始める','CONFIRM_NEW')}${button('戻る','CANCEL_NEW',true)}</nav>`);return start();}
    if(a==='CONFIRM_NEW')return start();
    if(state)apply({type:a});
  });
  document.addEventListener('keydown',e=>{if(e.repeat&&(['Enter',' '].includes(e.key)||/^[1-5]$/.test(e.key))){e.preventDefault();return;}if(modal.open||!state||e.ctrlKey||e.altKey||e.metaKey)return;if(/^[1-5]$/.test(e.key)){e.preventDefault();apply({type:'PLACE',column:Number(e.key)-1});}});
  modal.addEventListener('cancel',e=>{e.preventDefault();if(mode!=='RESULT'){close();if(state&&state.phase!==G.Phase.PLAYING)result();}});
  title();
})();
