// Optional development verification. Gameplay needs no Node.js or Playwright.
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
require('./game.test.js');const {Game:G,TestFixtures:F}=global.Shogun;
const base='http://127.0.0.1:4173/prototype/',root=path.resolve(__dirname,'..');
const sizes=[[320,568],[320,740],[375,667],[375,812],[1280,720],[740,320]];
const report={date:new Date().toISOString(),browsers:[]};
const assert=(v,m)=>{if(!v)throw Error(m);};
const pause=p=>p.waitForTimeout(230);
async function click(p,a){await pause(p);await p.locator(`[data-action="${a}"]`).click();}
async function state(p){return p.evaluate(()=>Shogun.Storage.createStorage().load().state);}
function playing(){const s=G.newGame();s.columns=F.columns(15,1);s.best=15;s.current={number:16,color:'western'};s.remaining=Array.from({length:9},(_,i)=>({number:17+i,color:'japanese'}));return F.sync(s);}
async function load(p,s){await p.goto(base);await p.evaluate(s=>{if(s){if(!Shogun.Storage.createStorage().save(s).ok)throw Error('invalid fixture');}else localStorage.removeItem(Shogun.Config.STORAGE_KEY);},s);await p.reload();if(s)await click(p,'RESUME');}
async function fits(p,label){const data=await p.evaluate(()=>{const d=document.documentElement,m=document.querySelector('dialog[open]'),scope=m||document.getElementById('app');const bad=[];for(const e of scope.querySelectorAll('button,h1,h2,p,small,.castle,.castle b,.kind,.stage,.scores,.score-preview,.four-info,.result-number,.rating,.blocked-castle')){const r=e.getBoundingClientRect();if(!r.width||!r.height)continue;if(r.left<-.5||r.top<-.5||r.right>innerWidth+.5||r.bottom>innerHeight+.5||e.scrollWidth>e.clientWidth+2&&e.clientWidth>0)bad.push({tag:e.tagName,cls:e.className,text:e.textContent,rect:[r.x,r.y,r.width,r.height],scroll:e.scrollWidth,client:e.clientWidth});}return{w:innerWidth,h:innerHeight,sw:d.scrollWidth,sh:d.scrollHeight,bad};});assert(data.sw<=data.w&&data.sh<=data.h&&data.bad.length===0,label+' '+JSON.stringify(data));return data;}
(async()=>{for(const channel of ['msedge','chrome']){const browser=await chromium.launch({channel,headless:true});try{const context=await browser.newContext({viewport:{width:375,height:667}}),p=await context.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).hostname!=='127.0.0.1')requests.push(r.url());});
await p.goto(base+'tests/ui.html');await p.waitForFunction(()=>window.UIResults,null,{timeout:90000});const suite=await p.evaluate(()=>UIResults);assert(!suite.failed,JSON.stringify(suite.results.filter(r=>!r.pass)));
const layouts=[];
for(const [width,height]of sizes){await p.setViewportSize({width,height});for(const [name,s]of [['title',null],['playing',playing()],['bonus',G.transition(F.win(),{type:'CONTINUE'}).state],['win',F.monoBlocked()],['fullwin',F.win()],['battle',F.arriveBlocked(18)],['final',F.final()]]){await load(p,s);layouts.push({name,...await fits(p,name)});if(channel==='msedge'&&['playing','win','final'].includes(name)){await p.screenshot({path:path.join(root,`docs/screenshots/compact-${name}-${width}x${height}.png`)});}if(s){const before=JSON.stringify(await state(p));await p.reload();await click(p,'RESUME');assert(JSON.stringify(await state(p))===before,'reload changed state');}}
await load(p,playing());assert(!await p.locator('body').textContent().then(t=>t.includes('再合戦')),'old retry UI');await click(p,'HELP');for(let i=0;i<10;i++){await fits(p,'help '+i);assert(!await p.locator('dialog').textContent().then(t=>t.includes('再合戦')),'old retry help');if(i<9)await click(p,'NEXT');}await p.keyboard.press('Escape');assert(!await p.locator('dialog').evaluate(d=>d.open),'help escape');await click(p,'DETAILS');for(let i=0;i<4;i++){await fits(p,'details '+i);if(i<3)await click(p,'NEXT');}await click(p,'CLOSE_HELP');}
// Long scores/rating and enlarged text, without clipping the navigation.
const long=F.final();long.scores=[999999,999999,18];long.finalScore=G.totalScore(long);
for(const [width,height]of [[320,568],[740,320]]){await p.setViewportSize({width,height});await load(p,long);await fits(p,'long score/rating');await load(p,playing());await p.addStyleTag({content:':root{font-size:20px}'});await fits(p,'125 percent text');await click(p,'HELP');for(let i=0;i<10;i++){await fits(p,'large help '+i);if(i<9)await click(p,'NEXT');}await click(p,'CLOSE_HELP');}
// Native inputs, including all three battles and replay, not synthetic click events.
await load(p,null);await p.locator('[data-action="NEW"]').focus();await p.keyboard.press('Enter');let steps=0;while((await state(p)).phase!==G.Phase.GAME_RESULT){const s=await state(p);assert(++steps<1000,'non terminating native game');if(s.phase===G.Phase.PLAYING){const i=G.available(s)[0];await pause(p);if(steps%2)await p.keyboard.press(String(i+1));else await p.locator(`[data-column="${i}"]`).click();}else await click(p,s.phase===G.Phase.WIN?'CONTINUE':'NEXT_BATTLE');}assert((await state(p)).ended===3,'three battles');await click(p,'NEW');assert(G.count(await state(p))===0,'replay');await p.locator('[data-column="0"]').focus();await pause(p);await p.keyboard.press('Space');assert(G.count(await state(p))===1,'space');
await click(p,'HELP');for(let i=0;i<8;i++)await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)),'focus trap');await p.keyboard.press('Escape');assert(await p.locator('[data-action="HELP"]').evaluate(e=>e===document.activeElement),'focus restore');
// Landscape rotation and browser visible-height changes use the same persisted state.
const prior=JSON.stringify(await state(p));for(const [width,height]of [[375,812],[740,320],[320,568]]){await p.setViewportSize({width,height});await fits(p,'rotate');}assert(JSON.stringify(await state(p))===prior,'resize mutation');
const touch=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,isMobile:true,reducedMotion:'reduce'});const t=await touch.newPage();await t.goto(base);await t.locator('[data-action="NEW"]').tap();await pause(t);await t.locator('[data-column="0"]').tap();assert(G.count(await state(t))===1,'touch');assert(await t.locator('.placed .top-castle').evaluate(e=>getComputedStyle(e).animationName)==='none','reduced animation');await fits(t,'touch');await touch.close();
const denied=await browser.newContext();await denied.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('denied');};Storage.prototype.getItem=function(){throw Error('denied');};});const d=await denied.newPage();await d.goto(base);await click(d,'NEW');assert(await d.locator('.message').textContent()==='保存できません。詳細を確認','save warning');await pause(d);await d.locator('[data-column="0"]').click();assert((await d.locator('.count strong').textContent()).startsWith('1'),'denied can play');await denied.close();
const missing=await browser.newContext();await missing.route('**/assets/castles/*.png',r=>r.abort());const m=await missing.newPage();await m.goto(base);await click(m,'NEW');assert(await m.locator('.current-art b').textContent(),'number without image');assert(await m.locator('.current-art .kind').textContent(),'type without image');await missing.close();
const local=await browser.newContext();const f=await local.newPage();await f.goto(pathToFileURL(path.join(root,'index.html')).href);await click(f,'NEW');await pause(f);await f.locator('[data-column="0"]').click();const saved=JSON.stringify(await state(f));await f.reload();await click(f,'RESUME');assert(JSON.stringify(await state(f))===saved,'file save');await local.close();
assert(!errors.length,errors.join('\n'));assert(!requests.length,'external requests');report.browsers.push({channel,version:browser.version(),suite,layouts,nativeSteps:steps,checks:['native mouse/keyboard/full game/replay','focus trap/restore','touch emulation/reduced motion','rotation/visible height','denied storage','missing images','file:// reload','HTTP repository prefix','no external requests','no console errors'],errors});console.log(channel+' passed '+suite.passed+' UI tests, '+layouts.length+' layouts');await context.close();}finally{await browser.close();}}fs.writeFileSync(path.join(root,'docs/browser-test-data.json'),JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
